---
# tasks file for postgres_instance


- name: Installing python-psycopg2 package
  apt:
    pkg: python-psycopg2
    state: present

- name: Create user
  postgres_user:
    user: "{{ item.db_user }}"
    password: "{{ item.db_password }}"
    roles: "{{ item.db_user_roles }}"
    state: present
  with_items: "{{ postgres_instance_dbs }}"

- name: Create database
  postgres_db:
    name: "{{ item.db_name }}"
    owner: "{{ item.db_user }}"
    state: present
  with_items: "{{ postgres_instance_dbs }}"

- name: Create schema
  postgres_schema:
    database: "{{ item.db_name }}"
    schema: "{{ item.db_schema }}"
    user: "{{ item.db_user }}"
    state: present
  with_items: "{{ postgres_instance_dbs }}"


#- name: Authorize user to connect its only database on local and on the network
#  blockinfile:
#    dest: "{{ postgres_instance_pg_hba_conf_file }}"
#    insertafter: EOF
#    block: |
#      # Authorize user {{ item.db_user }} to connect its only database on local and on the network
#      # "local" - Authorize user to connect to database on localhost
#      local   {{ item.db_user }}      {{ item.db_name }}                                   md5
#      # IPv4 local connections:
#      host   {{ item.db_user }}      {{ item.db_name }}            127.0.0.1/32            md5
#      # IPv6 local connections:
#      host    {{ item.db_user }}      {{ item.db_name }}           ::1/128                 md5
#    state: present
#  with_items: "{{ postgres_instance_dbs }}"

- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL"
  notify:
    - Restart PostgreSQL