---
- name: Copy goss tests file
  template:
      src: goss.j2
      dest: "/etc/postgresql/goss.yml"
      owner: root
      group: root
      mode: 0640

#TODO
#- name: Launch goss test
#  goss:
#    path: "/etc/postgresql/goss.yml"
#    format: json

- name: Remove goss test
  file:
    path: "/etc/postgresql/goss.yml"
    state: absent