---
# defaults file for postgres_instance
postgres_instance_version: 9.4
postgres_instance_conf_dir: "/etc/postgresql/{{postgres_instance_version}}/main"
postgres_instance_pg_hba_conf_file: "{{ postgres_instance_conf_dir }}/pg_hba.conf"
postgres_instance_dbs:
  - { db_user: '{{ db_user }}', db_password: "{{ db_password }}", db_user_roles: 'CREATEROLE CREATEUSER',  db_name: 'springboot', db_schema: 'springboot' }