---

- name: Create spring boot keystore directory
  file:
    path: "{{ springboot_keystore_directory }}"
    owner: "{{ springboot_user }}"
    group: "{{ springboot_group }}"
    state: directory
    recurse: yes

- name : Check tomcat keystore directory exists
  stat:
    path: "{{ springboot_keystore_file }}"
  register: springboot_keystore_file_exists

- name: Generating keystore and certifcate
  command: >
    $JAVA_HOME/bin/keytool -genkey -noprompt -trustcacerts -keyalg RSA -keysize 2048 -storetype {{ springboot_keystore_type }} -alias {{ springboot_keystore_alias }} -dname "{{ springboot_keystore_subj }}" -keypass {{ springboot_keystore_password }} -keystore {{ springboot_keystore_file }} -storepass {{ springboot_keystore_password }} -validity 3650
  when: not springboot_keystore_file_exists.stat.exists