---
# defaults file for springboot
springboot_user: springboot
springboot_group: springboot
springboot_main_directory: /opt/springboot
springboot_java_command: "java"
springboot_conf_directory: "{{ springboot_main_directory }}/conf"
springboot_jar_directory: "{{ springboot_main_directory }}/jar"
springboot_logs_directory: "{{ springboot_main_directory }}/logs"
springboot_logs_file: "{{ springboot_logs_directory }}/application.log"
springboot_nexus_url: "{{ nexus_url }}/service/local/artifact/maven/content"
springboot_apps_repository: "snapshots"
springboot_apps_groupid: "com.syscom"
springboot_apps_artifactid: "db-restfull"
springboot_apps_version: "LATEST"
springboot_apps_package: "jar"
springboot_apps_jar_name: "db-restfull.jar"
springboot_apps_conf_files:
 - { src: "application.properties.j2", dest: "{{ springboot_conf_directory }}/application.properties" }
 - { src: "db-service.properties.j2", dest: "{{ springboot_conf_directory }}/db-service.properties" }
springboot_http_port: 8080
springboot_https_port: 8443
springboot_iptables_enabled: False
springboot_network_interface: "eth0"

springboot_database: POSTGRESQL
springboot_datasource_patform: postgres
springboot_show_sql: true
springboot_database_driverClassName: "org.postgresql.Driver"
springboot_datasource_url: "jdbc:postgresql://localhost:5432/springboot?currentSchema=springboot"
# Parametre a définir suivant le cas d'utilisation. Pour ce cas, ces paramètres ont été redefinis via Ansible-Vault.
springboot_datasource_username:
springboot_datasource_password:

# Duree de validité d'un jeton d'authentification exprimé en minutes
springboot_token_duration: 120

#Paramètres du serveur de mail
springboot_mail_host: localhost
springboot_mail_port: 25
springboot_mail_username:
springboot_mail_password:
springboot_mail_properties_mail_smtp_auth:
springboot_mail_properties_mail_smtp_starttls_enable: