---
# defaults file for springboot
springboot_user: springboot
springboot_group: springboot
springboot_main_directory: /opt/springboot
springboot_conf_directory: "{{ springboot_main_directory }}/conf"
springboot_jar_directory: "{{ springboot_main_directory }}/jar"
springboot_logs_directory: "{{ springboot_main_directory }}/logs"
springboot_nexus_url: "{{ nexus_url }}/service/local/artifact/maven/content"
springboot_apps_repository: "snapshots"
springboot_apps_groupid: "com.syscom"
springboot_apps_artifactid: "db-restfull"
springboot_apps_version: "LATEST"
springboot_apps_package: "jar"
springboot_apps_jar_name: "db-restfull.jar"
springboot_apps_conf_files:
 - { src: "application.properties.j2", dest: "{{ springboot_conf_directory }}/application.properties" }
springboot_http_port: 8080
springboot_iptables_enabled: False
springboot_network_interface: "eth0"
